# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jordanoo
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dev-apps
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shortUri

custom:
  defaultStage: dev
  functionsPath: src/functions

build:
  esbuild:
    minify: true
    bundle: true
    sourcemap: false
    exclude:
      - 'rest/*'

package:
  individually: true

plugins:
  - serverless-offline

provider:
  name: aws
  region: sa-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: nodejs20.x
  architecture: arm64
  timeout: 150
  memorySize: 128
  iam:
    role: 
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource:
            - !GetAtt SitesRedirects.Arn

functions:
  hello:
    handler: ${self:custom.functionsPath}/hello.handler
    events:
      - httpApi: POST /

resources:
  Resources:
    SitesRedirects:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SitesRedirects
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
