# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jordanoo
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dev-apps
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shortUri

custom:
  defaultStage: dev

provider:
  name: aws
  region: sa-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: nodejs20.x
  architecture: arm64
  timeout: 150
  memorySize: 128

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi: POST /
