@hostAWS = https://pmhyq4xtq4.execute-api.sa-east-1.amazonaws.com
@hostLocal = http://localhost:3000/

###

### Create Site Rediret
POST {{hostAWS}}/
Content-Type: application/json

{
  "originalUrl": "aaaa"
}